import { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'zh' | 'en' | 'ja' | 'ko' | 'fr' | 'ru' | 'de';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  zh: {
    // Navbar
    'nav.home': '首页',
    'nav.features': '功能',
    'nav.showcase': '展示',
    'nav.preview': '预览',
    'nav.purchase': '购买',
    'nav.buyNow': '立即购买',

    // Hero
    'hero.title': '主宰你的游戏世界',
    'hero.subtitle': '专为网易版我的世界打造的高端客户端，提供流畅的游戏体验和强大的功能支持',
    'hero.feature1': '生存辅助',
    'hero.feature2': 'PVP 增强',
    'hero.feature3': 'HvH 常胜',
    'hero.feature4': '界面优化',
    'hero.watchPreview': '观看预览',

    // Features
    'features.title': '为什么选择 Fate?',
    'features.subtitle': '丰富的功能集，让你爱不释手',
    'features.rich': '功能丰富',
    'features.richDesc': '海量模块，多种自定义选项，满足你的所有需求',
    'features.easy': '简单易用',
    'features.easyDesc': '设计简洁直观，安装即用，无需复杂配置',
    'features.update': '持续更新',
    'features.updateDesc': '频繁更新，紧跟版本，为你带来最新功能',
    'features.platform': '全平台支持',
    'features.platformDesc': '适配 Android 8+，iOS（仍在进行测试）',
    'features.trust': '值得信赖',
    'features.trustDesc': '由资深开发者团队打造，服务数千玩家',
    'features.quality': '品质保证',
    'features.qualityDesc': '我们重视用户体验，致力于打造最优质的客户端',

    // Showcase
    'showcase.title': '功能展示',
    'showcase.subtitle': '探索 Fate Client 的强大功能',
    'showcase.hud': '游戏内 HUD',
    'showcase.hudDesc': '提供业界最好的视觉效果，带来震撼的视觉体验',
    'showcase.xray': '生存辅助',
    'showcase.xrayDesc': 'Xray, Instant Dig等功能',
    'showcase.pvp': 'PVP 增强',
    'showcase.pvpDesc': 'KillAura, TargetStrafe, Scaffold等功能',
    'showcase.config': '自定义配置',
    'showcase.configDesc': '丰富的设置选项，根据个人喜好调整客户端',
    'showcase.more': '更多功能等你发现',
    'showcase.moreDesc': 'Fate Client 拥有超过 50+ 个功能模块，涵盖游戏辅助、界面优化、性能提升等多个方面。购买体验，探索更多精彩内容。',

    // Video Preview
    'video.title': '视频预览',
    'video.subtitle': '观看演示视频，了解 Fate Client 的强大功能',
    'video.hint': '点击视频卡片跳转至 Bilibili 观看完整内容',

    // Purchase
    'purchase.title': '选择你的方案',
    'purchase.subtitle': '灵活的订阅方案，满足不同需求',
    'purchase.day': '天卡',
    'purchase.week': '周卡',
    'purchase.month': '月卡',
    'purchase.quarter': '季卡',
    'purchase.forever': '永久',
    'purchase.beta': 'Beta',
    'purchase.dayUnit': '天',
    'purchase.weekUnit': '周',
    'purchase.monthUnit': '月',
    'purchase.quarterUnit': '季',
    'purchase.foreverUnit': '永久',
    'purchase.popular': '最热',
    'purchase.betaFeatures': '专属功能',
    'purchase.betaFeature1': 'Godmode（适用于EaseCation）',
    'purchase.betaFeature2': '设备伪装（绕过服务器键鼠检测）',
    'purchase.betaFeature3': '以及更多的独享功能',
    'purchase.foreverFeature1': '伴随你的终身',
    'purchase.foreverFeature2': '一代传一代',
    'purchase.foreverFeature3': '人走端还在',
    'purchase.select': '选择',
    'purchase.copy': '复制',
    'purchase.copyAgentQQ': '复制代理QQ',
    'purchase.agentNote': '此时长无法在站内购买，请添加代理QQ',
    'purchase.addAgentQQ': '添加代理QQ',
    'purchase.chooseAgent': '请选择一位代理进行购买',
    'purchase.close': '关闭',
    'purchase.copied': '已复制',

    // Footer
    'footer.slogan': '主宰你的游戏世界。专为网易版我的世界打造的高端客户端。',
    'footer.product': '产品',
    'footer.support': '支持',
    'footer.legal': '法律',
    'footer.faq': '常见问题',
    'footer.contact': '联系我们',
    'footer.feedback': '反馈',
    'footer.terms': '服务条款',
    'footer.privacy': '隐私政策',
    'footer.rights': '专为网易版我的世界打造',
  },
  en: {
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.showcase': 'Showcase',
    'nav.preview': 'Preview',
    'nav.purchase': 'Purchase',
    'nav.buyNow': 'Buy Now',
    'hero.title': 'Dominate Your Game World',
    'hero.subtitle': 'A premium client built for NetEase Minecraft, providing smooth gameplay and powerful features',
    'hero.feature1': 'Survival Assist',
    'hero.feature2': 'PVP Enhanced',
    'hero.feature3': 'HvH Winner',
    'hero.feature4': 'UI Optimize',
    'hero.watchPreview': 'Watch Preview',
    'features.title': 'Why Choose Fate?',
    'features.subtitle': 'Rich feature set that you will love',
    'features.rich': 'Feature Rich',
    'features.richDesc': 'Massive modules with various customization options to meet all your needs',
    'features.easy': 'Easy to Use',
    'features.easyDesc': 'Simple and intuitive design, install and play, no complex configuration needed',
    'features.update': 'Regular Updates',
    'features.updateDesc': 'Frequent updates to keep you up to date with the latest features',
    'features.platform': 'Cross Platform',
    'features.platformDesc': 'Compatible with Android 8+, iOS (still in testing)',
    'features.trust': 'Trustworthy',
    'features.trustDesc': 'Built by experienced developers, serving thousands of players',
    'features.quality': 'Quality Assurance',
    'features.qualityDesc': 'We value user experience and strive to create the best client',
    'showcase.title': 'Feature Showcase',
    'showcase.subtitle': 'Explore the powerful features of Fate Client',
    'showcase.hud': 'In-Game HUD',
    'showcase.hudDesc': 'Provides the best visual effects in the industry, delivering a stunning visual experience',
    'showcase.xray': 'Survival Assist',
    'showcase.xrayDesc': 'Xray, Instant Dig and more',
    'showcase.pvp': 'PVP Enhanced',
    'showcase.pvpDesc': 'KillAura, TargetStrafe, Scaffold and more',
    'showcase.config': 'Custom Config',
    'showcase.configDesc': 'Rich settings options to customize the client to your preferences',
    'showcase.more': 'More Features Await',
    'showcase.moreDesc': 'Fate Client has over 50+ feature modules covering game assistance, UI optimization, performance enhancement and more. Purchase and explore more exciting content.',
    'video.title': 'Video Preview',
    'video.subtitle': 'Watch demo videos to learn about Fate Client\'s powerful features',
    'video.hint': 'Click video card to jump to Bilibili to watch full content',
    'purchase.title': 'Choose Your Plan',
    'purchase.subtitle': 'Flexible subscription plans to meet different needs',
    'purchase.day': 'Day Pass',
    'purchase.week': 'Week Pass',
    'purchase.month': 'Month Pass',
    'purchase.quarter': 'Quarter Pass',
    'purchase.forever': 'Lifetime',
    'purchase.beta': 'Beta',
    'purchase.dayUnit': 'day',
    'purchase.weekUnit': 'week',
    'purchase.monthUnit': 'month',
    'purchase.quarterUnit': 'quarter',
    'purchase.foreverUnit': 'forever',
    'purchase.popular': 'POPULAR',
    'purchase.betaFeatures': 'Exclusive Features',
    'purchase.betaFeature1': 'Godmode (for EaseCation)',
    'purchase.betaFeature2': 'Device spoofing (bypass server KB/M detection)',
    'purchase.betaFeature3': 'And more exclusive features',
    'purchase.foreverFeature1': 'Accompany you for life',
    'purchase.foreverFeature2': 'Pass down through generations',
    'purchase.foreverFeature3': 'The client lives on',
    'purchase.select': 'Select',
    'purchase.copy': 'Copy',
    'purchase.copyAgentQQ': 'Copy Agent QQ',
    'purchase.agentNote': 'This duration cannot be purchased on-site, please add agent QQ',
    'purchase.addAgentQQ': 'Add Agent QQ',
    'purchase.chooseAgent': 'Please choose an agent to purchase',
    'purchase.close': 'Close',
    'purchase.copied': 'Copied',
    'footer.slogan': 'Dominate your game world. A premium client built for NetEase Minecraft.',
    'footer.product': 'Product',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact Us',
    'footer.feedback': 'Feedback',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.rights': 'Built for NetEase Minecraft',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.features': '機能',
    'nav.showcase': 'ショーケース',
    'nav.preview': 'プレビュー',
    'nav.purchase': '購入',
    'nav.buyNow': '今すぐ購入',
    'hero.title': 'ゲーム世界を支配する',
    'hero.subtitle': 'NetEase版Minecraftのためのプレミアムクライアント。スムーズなゲームプレイと強力な機能を提供します',
    'hero.feature1': 'サバイバル支援',
    'hero.feature2': 'PVP強化',
    'hero.feature3': 'HvH常勝',
    'hero.feature4': 'UI最適化',
    'hero.watchPreview': 'プレビューを見る',
    'features.title': 'なぜFateを選ぶのか?',
    'features.subtitle': 'あなたが気に入る豊富な機能セット',
    'features.rich': '機能が豊富',
    'features.richDesc': '多数のモジュールとカスタマイズオプションで、あらゆるニーズに対応',
    'features.easy': '使いやすい',
    'features.easyDesc': 'シンプルで直感的なデザイン。インストールしてすぐにプレイ、複雑な設定は不要',
    'features.update': '定期的なアップデート',
    'features.updateDesc': '頻繁なアップデートで、常に最新機能を提供',
    'features.platform': 'マルチプラットフォーム',
    'features.platformDesc': 'Android 8+、iOS（テスト中）に対応',
    'features.trust': '信頼できる',
    'features.trustDesc': '経験豊富な開発者チームが構築、数千人のプレイヤーをサポート',
    'features.quality': '品質保証',
    'features.qualityDesc': 'ユーザーエクスペリエンスを重視し、最高のクライアントを目指しています',
    'showcase.title': '機能ショーケース',
    'showcase.subtitle': 'Fate Clientの強力な機能を探索',
    'showcase.hud': 'ゲーム内HUD',
    'showcase.hudDesc': '業界最高の視覚効果を提供し、圧倒的な視覚体験をもたらします',
    'showcase.xray': 'サバイバル支援',
    'showcase.xrayDesc': 'Xray、Instant Digなど',
    'showcase.pvp': 'PVP強化',
    'showcase.pvpDesc': 'KillAura、TargetStrafe、Scaffoldなど',
    'showcase.config': 'カスタム設定',
    'showcase.configDesc': '豊富な設定オプションで、お好みに合わせてカスタマイズ',
    'showcase.more': 'さらに多くの機能',
    'showcase.moreDesc': 'Fate Clientには50以上の機能モジュールがあり、ゲーム支援、UI最適化、パフォーマンス向上などをカバーしています。購入して、さらにエキサイティングなコンテンツを探索してください。',
    'video.title': '動画プレビュー',
    'video.subtitle': 'デモ動画を見て、Fate Clientの強力な機能を知る',
    'video.hint': '動画カードをクリックしてBilibiliにジャンプし、フルコンテンツを視聴',
    'purchase.title': 'プランを選択',
    'purchase.subtitle': 'さまざまなニーズに対応する柔軟なサブスクリプションプラン',
    'purchase.day': '1日パス',
    'purchase.week': '1週間パス',
    'purchase.month': '1ヶ月パス',
    'purchase.quarter': '3ヶ月パス',
    'purchase.forever': '永久',
    'purchase.beta': 'Beta',
    'purchase.dayUnit': '日',
    'purchase.weekUnit': '週',
    'purchase.monthUnit': '月',
    'purchase.quarterUnit': '四半期',
    'purchase.foreverUnit': '永久',
    'purchase.popular': '人気',
    'purchase.betaFeatures': '独占機能',
    'purchase.betaFeature1': 'Godmode（EaseCation対応）',
    'purchase.betaFeature2': 'デバイス偽装（サーバーKB/M検出を回避）',
    'purchase.betaFeature3': 'さらに多くの独占機能',
    'purchase.foreverFeature1': '一生の伴侶',
    'purchase.foreverFeature2': '代々受け継がれる',
    'purchase.foreverFeature3': '人は去ってもクライアントは残る',
    'purchase.select': '選択',
    'purchase.copy': 'コピー',
    'purchase.copyAgentQQ': '代理QQをコピー',
    'purchase.agentNote': 'この期間はサイト内で購入できません。代理QQを追加してください',
    'purchase.addAgentQQ': '代理QQを追加',
    'purchase.chooseAgent': '購入する代理を選択してください',
    'purchase.close': '閉じる',
    'purchase.copied': 'コピー済み',
    'footer.slogan': 'ゲーム世界を支配する。NetEase版Minecraftのためのプレミアムクライアント。',
    'footer.product': '製品',
    'footer.support': 'サポート',
    'footer.legal': '法的事項',
    'footer.faq': 'よくある質問',
    'footer.contact': 'お問い合わせ',
    'footer.feedback': 'フィードバック',
    'footer.terms': '利用規約',
    'footer.privacy': 'プライバシーポリシー',
    'footer.rights': 'NetEase版Minecraft専用',
  },
  ko: {
    'nav.home': '홈',
    'nav.features': '기능',
    'nav.showcase': '쇼케이스',
    'nav.preview': '미리보기',
    'nav.purchase': '구매',
    'nav.buyNow': '지금 구매',
    'hero.title': '게임 세계를 지배하다',
    'hero.subtitle': 'NetEase Minecraft를 위한 프리미엄 클라이언트로 부드러운 게임플레이와 강력한 기능을 제공합니다',
    'hero.feature1': '서바이벌 지원',
    'hero.feature2': 'PVP 강화',
    'hero.feature3': 'HvH 승리',
    'hero.feature4': 'UI 최적화',
    'hero.watchPreview': '미리보기 보기',
    'features.title': '왜 Fate를 선택하나요?',
    'features.subtitle': '마음에 드는 풍부한 기능 세트',
    'features.rich': '풍부한 기능',
    'features.richDesc': '다양한 맞춤 설정 옵션을 가진 수많은 모듈로 모든 요구를 충족',
    'features.easy': '사용하기 쉬움',
    'features.easyDesc': '간단하고 직관적인 디자인. 설치하고 즉시 플레이, 복잡한 설정 불필요',
    'features.update': '정기 업데이트',
    'features.updateDesc': '빈번한 업데이트로 항상 최신 기능 제공',
    'features.platform': '크로스 플랫폼',
    'features.platformDesc': 'Android 8+, iOS(테스트 중) 호환',
    'features.trust': '신뢰할 수 있음',
    'features.trustDesc': '경험 풍부한 개발자 팀이 구축, 수천 명의 플레이어 서비스',
    'features.quality': '품질 보증',
    'features.qualityDesc': '사용자 경험을 중시하며 최고의 클라이언트를 만들기 위해 노력합니다',
    'showcase.title': '기능 쇼케이스',
    'showcase.subtitle': 'Fate Client의 강력한 기능 탐색',
    'showcase.hud': '인게임 HUD',
    'showcase.hudDesc': '업계 최고의 시각적 효과를 제공하여 놀라운 시각적 경험을 선사합니다',
    'showcase.xray': '서바이벌 지원',
    'showcase.xrayDesc': 'Xray, Instant Dig 등',
    'showcase.pvp': 'PVP 강화',
    'showcase.pvpDesc': 'KillAura, TargetStrafe, Scaffold 등',
    'showcase.config': '사용자 설정',
    'showcase.configDesc': '풍부한 설정 옵션으로 취향에 맞게 사용자 정의',
    'showcase.more': '더 많은 기능',
    'showcase.moreDesc': 'Fate Client에는 50개 이상의 기능 모듈이 있어 게임 지원, UI 최적화, 성능 향상 등을 다룹니다. 구매하고 더 흥미로운 콘텐츠를 탐색하세요.',
    'video.title': '동영상 미리보기',
    'video.subtitle': '데모 동영상을 보고 Fate Client의 강력한 기능 알아보기',
    'video.hint': '동영상 카드를 클릭하여 Bilibili로 이동하고 전체 콘텐츠 시청',
    'purchase.title': '플랜 선택',
    'purchase.subtitle': '다양한 요구를 충족하는 유연한 구독 플랜',
    'purchase.day': '1일 패스',
    'purchase.week': '1주 패스',
    'purchase.month': '1개월 패스',
    'purchase.quarter': '3개월 패스',
    'purchase.forever': '영구',
    'purchase.beta': 'Beta',
    'purchase.dayUnit': '일',
    'purchase.weekUnit': '주',
    'purchase.monthUnit': '월',
    'purchase.quarterUnit': '분기',
    'purchase.foreverUnit': '영구',
    'purchase.popular': '인기',
    'purchase.betaFeatures': '독점 기능',
    'purchase.betaFeature1': 'Godmode (EaseCation용)',
    'purchase.betaFeature2': '장치 스푸핑 (서버 KB/M 감지 우회)',
    'purchase.betaFeature3': '더 많은 독점 기능',
    'purchase.foreverFeature1': '평생의 동반자',
    'purchase.foreverFeature2': '대대로 물려받는',
    'purchase.foreverFeature3': '사람은 떠나도 클라이언트는 남는다',
    'purchase.select': '선택',
    'purchase.copy': '복사',
    'purchase.copyAgentQQ': '대리 QQ 복사',
    'purchase.agentNote': '이 기간은 사이트 내에서 구매할 수 없습니다. 대리 QQ를 추가하세요',
    'purchase.addAgentQQ': '대리 QQ 추가',
    'purchase.chooseAgent': '구매할 대리를 선택하세요',
    'purchase.close': '닫기',
    'purchase.copied': '복사됨',
    'footer.slogan': '게임 세계를 지배하다. NetEase Minecraft를 위한 프리미엄 클라이언트.',
    'footer.product': '제품',
    'footer.support': '지원',
    'footer.legal': '법률',
    'footer.faq': '자주 묻는 질문',
    'footer.contact': '문의하기',
    'footer.feedback': '피드백',
    'footer.terms': '서비스 약관',
    'footer.privacy': '개인정보 처리방침',
    'footer.rights': 'NetEase Minecraft 전용',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.features': 'Fonctionnalités',
    'nav.showcase': 'Vitrine',
    'nav.preview': 'Aperçu',
    'nav.purchase': 'Achat',
    'nav.buyNow': 'Acheter',
    'hero.title': 'Dominez Votre Monde de Jeu',
    'hero.subtitle': 'Un client premium conçu pour NetEase Minecraft, offrant un gameplay fluide et des fonctionnalités puissantes',
    'hero.feature1': 'Assistance Survie',
    'hero.feature2': 'PVP Amélioré',
    'hero.feature3': 'Vainqueur HvH',
    'hero.feature4': 'Optimisation UI',
    'hero.watchPreview': 'Voir l\'Aperçu',
    'features.title': 'Pourquoi Choisir Fate?',
    'features.subtitle': 'Un ensemble de fonctionnalités riches que vous allez adorer',
    'features.rich': 'Fonctionnalités Riches',
    'features.richDesc': 'Modules massifs avec diverses options de personnalisation pour répondre à tous vos besoins',
    'features.easy': 'Facile à Utiliser',
    'features.easyDesc': 'Design simple et intuitif, installez et jouez, aucune configuration complexe nécessaire',
    'features.update': 'Mises à Jour Régulières',
    'features.updateDesc': 'Mises à jour fréquentes pour vous tenir au courant des dernières fonctionnalités',
    'features.platform': 'Multiplateforme',
    'features.platformDesc': 'Compatible avec Android 8+, iOS (toujours en test)',
    'features.trust': 'Digne de Confiance',
    'features.trustDesc': 'Construit par une équipe de développeurs expérimentés, desservant des milliers de joueurs',
    'features.quality': 'Assurance Qualité',
    'features.qualityDesc': 'Nous valorisons l\'expérience utilisateur et nous efforçons de créer le meilleur client',
    'showcase.title': 'Vitrine des Fonctionnalités',
    'showcase.subtitle': 'Explorez les fonctionnalités puissantes de Fate Client',
    'showcase.hud': 'HUD en Jeu',
    'showcase.hudDesc': 'Fournit les meilleurs effets visuels de l\'industrie, offrant une expérience visuelle époustouflante',
    'showcase.xray': 'Assistance Survie',
    'showcase.xrayDesc': 'Xray, Instant Dig et plus',
    'showcase.pvp': 'PVP Amélioré',
    'showcase.pvpDesc': 'KillAura, TargetStrafe, Scaffold et plus',
    'showcase.config': 'Config Personnalisée',
    'showcase.configDesc': 'Options de paramètres riches pour personnaliser le client selon vos préférences',
    'showcase.more': 'Plus de Fonctionnalités',
    'showcase.moreDesc': 'Fate Client possède plus de 50+ modules de fonctionnalités couvrant l\'assistance de jeu, l\'optimisation UI, l\'amélioration des performances et plus. Achetez et explorez plus de contenu passionnant.',
    'video.title': 'Aperçu Vidéo',
    'video.subtitle': 'Regardez des vidéos de démonstration pour en savoir plus sur les fonctionnalités puissantes de Fate Client',
    'video.hint': 'Cliquez sur la carte vidéo pour accéder à Bilibili et regarder le contenu complet',
    'purchase.title': 'Choisissez Votre Plan',
    'purchase.subtitle': 'Plans d\'abonnement flexibles pour répondre à différents besoins',
    'purchase.day': 'Pass 1 Jour',
    'purchase.week': 'Pass 1 Semaine',
    'purchase.month': 'Pass 1 Mois',
    'purchase.quarter': 'Pass 3 Mois',
    'purchase.forever': 'À Vie',
    'purchase.beta': 'Beta',
    'purchase.dayUnit': 'jour',
    'purchase.weekUnit': 'semaine',
    'purchase.monthUnit': 'mois',
    'purchase.quarterUnit': 'trimestre',
    'purchase.foreverUnit': 'à vie',
    'purchase.popular': 'POPULAIRE',
    'purchase.betaFeatures': 'Fonctionnalités Exclusives',
    'purchase.betaFeature1': 'Godmode (pour EaseCation)',
    'purchase.betaFeature2': 'Usurpation d\'appareil (contournement de la détection KB/M du serveur)',
    'purchase.betaFeature3': 'Et plus de fonctionnalités exclusives',
    'purchase.foreverFeature1': 'Vous accompagne toute la vie',
    'purchase.foreverFeature2': 'Transmis de génération en génération',
    'purchase.foreverFeature3': 'Le client perdure',
    'purchase.select': 'Sélectionner',
    'purchase.copy': 'Copier',
    'purchase.copyAgentQQ': 'Copier QQ Agent',
    'purchase.agentNote': 'Cette durée ne peut pas être achetée sur le site, veuillez ajouter l\'agent QQ',
    'purchase.addAgentQQ': 'Ajouter Agent QQ',
    'purchase.chooseAgent': 'Veuillez choisir un agent pour acheter',
    'purchase.close': 'Fermer',
    'purchase.copied': 'Copié',
    'footer.slogan': 'Dominez votre monde de jeu. Un client premium conçu pour NetEase Minecraft.',
    'footer.product': 'Produit',
    'footer.support': 'Support',
    'footer.legal': 'Légal',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contactez-nous',
    'footer.feedback': 'Retour',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.rights': 'Conçu pour NetEase Minecraft',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.features': 'Функции',
    'nav.showcase': 'Витрина',
    'nav.preview': 'Предпросмотр',
    'nav.purchase': 'Покупка',
    'nav.buyNow': 'Купить',
    'hero.title': 'Доминируйте в Вашем Игровом Мире',
    'hero.subtitle': 'Премиум-клиент для NetEase Minecraft, обеспечивающий плавный геймплей и мощные функции',
    'hero.feature1': 'Помощь в Выживании',
    'hero.feature2': 'Улучшенный PVP',
    'hero.feature3': 'Победитель HvH',
    'hero.feature4': 'Оптимизация UI',
    'hero.watchPreview': 'Смотреть Предпросмотр',
    'features.title': 'Почему Выбирают Fate?',
    'features.subtitle': 'Богатый набор функций, который вам понравится',
    'features.rich': 'Богатые Функции',
    'features.richDesc': 'Массовые модули с различными вариантами настройки для удовлетворения всех ваших потребностей',
    'features.easy': 'Прост в Использовании',
    'features.easyDesc': 'Простой и интуитивно понятный дизайн, установите и играйте, без сложной настройки',
    'features.update': 'Регулярные Обновления',
    'features.updateDesc': 'Частые обновления, чтобы держать вас в курсе последних функций',
    'features.platform': 'Кроссплатформенный',
    'features.platformDesc': 'Совместим с Android 8+, iOS (все еще в тестировании)',
    'features.trust': 'Надежный',
    'features.trustDesc': 'Создан командой опытных разработчиков, обслуживающих тысячи игроков',
    'features.quality': 'Гарантия Качества',
    'features.qualityDesc': 'Мы ценим пользовательский опыт и стремимся создать лучший клиент',
    'showcase.title': 'Витрина Функций',
    'showcase.subtitle': 'Исследуйте мощные функции Fate Client',
    'showcase.hud': 'Внутриигровой HUD',
    'showcase.hudDesc': 'Обеспечивает лучшие визуальные эффекты в отрасли, обеспечивая потрясающий визуальный опыт',
    'showcase.xray': 'Помощь в Выживании',
    'showcase.xrayDesc': 'Xray, Instant Dig и многое другое',
    'showcase.pvp': 'Улучшенный PVP',
    'showcase.pvpDesc': 'KillAura, TargetStrafe, Scaffold и многое другое',
    'showcase.config': 'Пользовательская Конфигурация',
    'showcase.configDesc': 'Богатые опции настроек для настройки клиента по вашим предпочтениям',
    'showcase.more': 'Больше Функций',
    'showcase.moreDesc': 'Fate Client имеет более 50+ функциональных модулей, охватывающих помощь в игре, оптимизацию UI, повышение производительности и многое другое. Купите и исследуйте больше захватывающего контента.',
    'video.title': 'Видео Предпросмотр',
    'video.subtitle': 'Смотрите демонстрационные видео, чтобы узнать о мощных функциях Fate Client',
    'video.hint': 'Нажмите на карточку видео, чтобы перейти на Bilibili и посмотреть полный контент',
    'purchase.title': 'Выберите Ваш План',
    'purchase.subtitle': 'Гибкие планы подписки для различных потребностей',
    'purchase.day': 'Пропуск на 1 День',
    'purchase.week': 'Пропуск на 1 Неделю',
    'purchase.month': 'Пропуск на 1 Месяц',
    'purchase.quarter': 'Пропуск на 3 Месяца',
    'purchase.forever': 'Пожизненный',
    'purchase.beta': 'Beta',
    'purchase.dayUnit': 'день',
    'purchase.weekUnit': 'неделя',
    'purchase.monthUnit': 'месяц',
    'purchase.quarterUnit': 'квартал',
    'purchase.foreverUnit': 'пожизненно',
    'purchase.popular': 'ПОПУЛЯРНЫЙ',
    'purchase.betaFeatures': 'Эксклюзивные Функции',
    'purchase.betaFeature1': 'Godmode (для EaseCation)',
    'purchase.betaFeature2': 'Подмена устройства (обход обнаружения KB/M сервера)',
    'purchase.betaFeature3': 'И многие другие эксклюзивные функции',
    'purchase.foreverFeature1': 'Сопровождает вас всю жизнь',
    'purchase.foreverFeature2': 'Передается из поколения в поколение',
    'purchase.foreverFeature3': 'Клиент живет вечно',
    'purchase.select': 'Выбрать',
    'purchase.copy': 'Копировать',
    'purchase.copyAgentQQ': 'Копировать QQ Агента',
    'purchase.agentNote': 'Эту продолжительность нельзя купить на сайте, пожалуйста, добавьте агента QQ',
    'purchase.addAgentQQ': 'Добавить Агента QQ',
    'purchase.chooseAgent': 'Пожалуйста, выберите агента для покупки',
    'purchase.close': 'Закрыть',
    'purchase.copied': 'Скопировано',
    'footer.slogan': 'Доминируйте в вашем игровом мире. Премиум-клиент для NetEase Minecraft.',
    'footer.product': 'Продукт',
    'footer.support': 'Поддержка',
    'footer.legal': 'Юридическая',
    'footer.faq': 'Частые Вопросы',
    'footer.contact': 'Свяжитесь с Нами',
    'footer.feedback': 'Обратная Связь',
    'footer.terms': 'Условия Использования',
    'footer.privacy': 'Политика Конфиденциальности',
    'footer.rights': 'Создано для NetEase Minecraft',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.features': 'Funktionen',
    'nav.showcase': 'Vitrine',
    'nav.preview': 'Vorschau',
    'nav.purchase': 'Kauf',
    'nav.buyNow': 'Jetzt Kaufen',
    'hero.title': 'Beherrschen Sie Ihre Spielwelt',
    'hero.subtitle': 'Ein Premium-Client für NetEase Minecraft, der reibungsloses Gameplay und leistungsstarke Funktionen bietet',
    'hero.feature1': 'Überlebenshilfe',
    'hero.feature2': 'PVP Verbessert',
    'hero.feature3': 'HvH Sieger',
    'hero.feature4': 'UI Optimierung',
    'hero.watchPreview': 'Vorschau Ansehen',
    'features.title': 'Warum Fate Wählen?',
    'features.subtitle': 'Ein reichhaltiger Funktionsumfang, den Sie lieben werden',
    'features.rich': 'Funktionsreich',
    'features.richDesc': 'Massive Module mit verschiedenen Anpassungsoptionen, um alle Ihre Bedürfnisse zu erfüllen',
    'features.easy': 'Einfach zu Bedienen',
    'features.easyDesc': 'Einfaches und intuitives Design, installieren und spielen, keine komplexe Konfiguration erforderlich',
    'features.update': 'Regelmäßige Updates',
    'features.updateDesc': 'Häufige Updates, um Sie auf dem neuesten Stand der Funktionen zu halten',
    'features.platform': 'Plattformübergreifend',
    'features.platformDesc': 'Kompatibel mit Android 8+, iOS (noch im Test)',
    'features.trust': 'Vertrauenswürdig',
    'features.trustDesc': 'Entwickelt von einem erfahrenen Entwicklerteam, das Tausende von Spielern bedient',
    'features.quality': 'Qualitätssicherung',
    'features.qualityDesc': 'Wir schätzen die Benutzererfahrung und bemühen uns, den besten Client zu erstellen',
    'showcase.title': 'Funktionsvitrine',
    'showcase.subtitle': 'Erkunden Sie die leistungsstarken Funktionen von Fate Client',
    'showcase.hud': 'In-Game HUD',
    'showcase.hudDesc': 'Bietet die besten visuellen Effekte der Branche und ein atemberaubendes visuelles Erlebnis',
    'showcase.xray': 'Überlebenshilfe',
    'showcase.xrayDesc': 'Xray, Instant Dig und mehr',
    'showcase.pvp': 'PVP Verbessert',
    'showcase.pvpDesc': 'KillAura, TargetStrafe, Scaffold und mehr',
    'showcase.config': 'Benutzerdefinierte Konfiguration',
    'showcase.configDesc': 'Reiche Einstellungsoptionen, um den Client nach Ihren Vorlieben anzupassen',
    'showcase.more': 'Mehr Funktionen',
    'showcase.moreDesc': 'Fate Client verfügt über 50+ Funktionsmodule, die Spielhilfe, UI-Optimierung, Leistungsverbesserung und mehr abdecken. Kaufen Sie und erkunden Sie mehr aufregende Inhalte.',
    'video.title': 'Video Vorschau',
    'video.subtitle': 'Sehen Sie sich Demo-Videos an, um mehr über die leistungsstarken Funktionen von Fate Client zu erfahren',
    'video.hint': 'Klicken Sie auf die Videokarte, um zu Bilibili zu springen und den vollständigen Inhalt anzusehen',
    'purchase.title': 'Wählen Sie Ihren Plan',
    'purchase.subtitle': 'Flexible Abonnementpläne für verschiedene Bedürfnisse',
    'purchase.day': '1-Tages-Pass',
    'purchase.week': '1-Wochen-Pass',
    'purchase.month': '1-Monats-Pass',
    'purchase.quarter': '3-Monats-Pass',
    'purchase.forever': 'Lebenslang',
    'purchase.beta': 'Beta',
    'purchase.dayUnit': 'Tag',
    'purchase.weekUnit': 'Woche',
    'purchase.monthUnit': 'Monat',
    'purchase.quarterUnit': 'Quartal',
    'purchase.foreverUnit': 'lebenslang',
    'purchase.popular': 'BELIEBT',
    'purchase.betaFeatures': 'Exklusive Funktionen',
    'purchase.betaFeature1': 'Godmode (für EaseCation)',
    'purchase.betaFeature2': 'Geräte-Spoofing (Umgehung der Server KB/M-Erkennung)',
    'purchase.betaFeature3': 'Und weitere exklusive Funktionen',
    'purchase.foreverFeature1': 'Begleitet Sie ein Leben lang',
    'purchase.foreverFeature2': 'Von Generation zu Generation weitergegeben',
    'purchase.foreverFeature3': 'Der Client lebt weiter',
    'purchase.select': 'Auswählen',
    'purchase.copy': 'Kopieren',
    'purchase.copyAgentQQ': 'Agent QQ Kopieren',
    'purchase.agentNote': 'Diese Dauer kann nicht vor Ort gekauft werden, bitte fügen Sie den Agenten QQ hinzu',
    'purchase.addAgentQQ': 'Agent QQ Hinzufügen',
    'purchase.chooseAgent': 'Bitte wählen Sie einen Agenten zum Kauf aus',
    'purchase.close': 'Schließen',
    'purchase.copied': 'Kopiert',
    'footer.slogan': 'Beherrschen Sie Ihre Spielwelt. Ein Premium-Client für NetEase Minecraft.',
    'footer.product': 'Produkt',
    'footer.support': 'Support',
    'footer.legal': 'Rechtliches',
    'footer.faq': 'FAQ',
    'footer.contact': 'Kontaktieren Sie Uns',
    'footer.feedback': 'Feedback',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.rights': 'Für NetEase Minecraft entwickelt',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
